import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#333535',
        'surface-bright': '#38393a',
        'tertiary-fixed-dim': '#eeb9bd',
        'outline-variant': '#3c4b36',
        'surface-container': '#1e2020',
        'tertiary': '#ffefef',
        'surface': '#121414',
        'border-subtle': '#30363D',
        'primary-container': '#4af626',
        'on-secondary-fixed-variant': '#683d00',
        'primary': '#d4ffc1',
        'surface-dim': '#121414',
        'on-tertiary-fixed-variant': '#623c40',
        'text-muted': '#B8B8B8',
        'secondary-container': '#ed9000',
        'bg-surface': '#15181E',
        'on-background': '#e2e2e2',
        'on-primary-fixed-variant': '#0c5300',
        'surface-tint': '#34e507',
        'primary-fixed': '#79ff59',
        'surface-variant': '#333535',
        'on-secondary-container': '#583300',
        'on-primary-container': '#136c00',
        'inverse-primary': '#136e00',
        'bg-main': '#0B0C0F',
        'on-secondary-fixed': '#2c1700',
        'on-primary': '#063900',
        'on-primary-fixed': '#022100',
        'on-error': '#690005',
        'error-container': '#93000a',
        'glow-green': 'rgba(74, 246, 38, 0.25)',
        'surface-container-low': '#1a1c1c',
        'tertiary-container': '#ffc9cd',
        'background': '#121414',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#ffdcbc',
        'outline': '#86957d',
        'inverse-surface': '#e2e2e2',
        'error': '#ffb4ab',
        'on-tertiary': '#48272a',
        'on-surface-variant': '#bbccb0',
        'tertiary-fixed': '#ffdadc',
        'surface-container-lowest': '#0c0f0f',
        'primary-fixed-dim': '#34e507',
        'surface-container-high': '#282a2b',
        'inverse-on-surface': '#2f3131',
        'secondary': '#ffb86b',
        'on-surface': '#e2e2e2',
        'on-secondary': '#492900',
        'secondary-fixed-dim': '#ffb86b',
        'on-tertiary-fixed': '#301216',
        'on-tertiary-container': '#7b5256',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'gutter': '24px',
        'max-width': '1200px',
        'container-padding': '16px',
        'section-gap': '120px',
        'section-gap-mobile': '64px',
      },
      fontFamily: {
        'headline-md': ['IBM Plex Mono', 'monospace'],
        'display-lg-mobile': ['IBM Plex Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['IBM Plex Mono', 'monospace'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        flicker: 'flicker 0.15s infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        flicker: {
          '0%': { opacity: '0.27861' },
          '5%': { opacity: '0.34769' },
          '10%': { opacity: '0.23604' },
          '15%': { opacity: '0.90626' },
          '20%': { opacity: '0.18128' },
          '25%': { opacity: '0.83891' },
          '30%': { opacity: '0.65583' },
          '35%': { opacity: '0.57807' },
          '40%': { opacity: '0.26559' },
          '45%': { opacity: '0.84693' },
          '50%': { opacity: '0.96019' },
          '55%': { opacity: '0.08594' },
          '60%': { opacity: '0.20313' },
          '65%': { opacity: '0.71988' },
          '70%': { opacity: '0.53455' },
          '75%': { opacity: '0.37288' },
          '80%': { opacity: '0.71428' },
          '85%': { opacity: '0.70419' },
          '90%': { opacity: '0.7003' },
          '95%': { opacity: '0.36108' },
          '100%': { opacity: '0.24387' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
